package protobuf

import (
	"fmt"

	"github.com/yangjerry110/tool/internal/cmd/template"
)

type ProtobufMessageField struct {
	MessageName string
	FieldName   string
	FieldGap    string
}

type ProtobufMessage struct {
	ProjectPath string
	FileName    string
	Fields      []*ProtobufMessageField
}

/**
 * @description: New
 * @author: Jerry.Yang
 * @date: 2025-03-03 14:19:19
 * @return {*}
 */
func (i *ProtobufMessage) New() error {
	if err := template.SaveTemplate(fmt.Sprintf("%s/vo/protobuf", i.ProjectPath), fmt.Sprintf("%s_message.go", i.FileName), i.getTemplate(), i); err != nil {
		return err
	}
	return nil
}

/**
 * @description: getTemplate
 * @author: Jerry.Yang
 * @date: 2025-03-03 14:19:10
 * @return {*}
 */
func (p *ProtobufMessage) getTemplate() string {
	return `
	// Code generated by protoc-gen-tool. DO NOT EDIT.
// Source: region

package protobuf

{{- range .Fields}}
func (x *{{.MessageName}}) Has{{.FieldName}}() bool {
	return x.{{.FieldName}} != nil
}
{{.FieldGap}}
{{- end}}

	`
}
